version: '3.3'
services:
  fluentd:
    image: ${DOCKERHUB_USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net 

  elasticsearch:
    image: elasticsearch:6.7.0
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net

  kibana:
    image: kibana:6.7.0
    ports:
      - "5601:5601"
    networks:
      - back_net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      front_net:
        aliases:
          - zipkin
      back_net:
        aliases:
          - zipkin
networks:
  back_net:
  front_net:
