version: '3.3'
services:

  ui:
    image: ${DOCKERHUB_USERNAME}/search_engine_ui:${UI_VER}
    ports:
      - ${UI_OUT_PORT}:${UI_IN_PORT}/tcp
    networks:
      - front_net
      - back_net
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: service.ui

  engine:
    image: ${DOCKERHUB_USERNAME}/search_engine_crawler:${ENGINE_VER}
    networks:
      - back_net
 #   logging:
 #     driver: "fluentd"
 #     options:
 #       fluentd-address: localhost:24224
 #       tag: service.engine

networks:
  front_net:
  back_net:
